name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DB_USER : postgres
  DB_PASS : postgres
  DB_NAME : testing
  DB_HOST : localhost
  DB_DIALECT : postgres
  NODE_ENV : test
  APP_PORT : 4000
  SECRET : TOP_SECRET
  
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: unit test
        run: npm run test
      # - name: e2e test
      #   run: npm run test:e2e
      # - name: lint code
      #   run: npm run lint